// Generated by gencpp from file tsane_mmlamare_mwpiazza_lab4/AStar.msg
// DO NOT EDIT!


#ifndef TSANE_MMLAMARE_MWPIAZZA_LAB4_MESSAGE_ASTAR_H
#define TSANE_MMLAMARE_MWPIAZZA_LAB4_MESSAGE_ASTAR_H

#include <ros/service_traits.h>


#include <tsane_mmlamare_mwpiazza_lab4/AStarRequest.h>
#include <tsane_mmlamare_mwpiazza_lab4/AStarResponse.h>


namespace tsane_mmlamare_mwpiazza_lab4
{

struct AStar
{

typedef AStarRequest Request;
typedef AStarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AStar
} // namespace tsane_mmlamare_mwpiazza_lab4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStar > {
  static const char* value()
  {
    return "0e3cd40f90d5ac4d7658bc4cfa360931";
  }

  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStar&) { return value(); }
};

template<>
struct DataType< ::tsane_mmlamare_mwpiazza_lab4::AStar > {
  static const char* value()
  {
    return "tsane_mmlamare_mwpiazza_lab4/AStar";
  }

  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStar&) { return value(); }
};


// service_traits::MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest> should match 
// service_traits::MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStar > 
template<>
struct MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStar >::value();
  }
  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest> should match 
// service_traits::DataType< ::tsane_mmlamare_mwpiazza_lab4::AStar > 
template<>
struct DataType< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest>
{
  static const char* value()
  {
    return DataType< ::tsane_mmlamare_mwpiazza_lab4::AStar >::value();
  }
  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStarResponse> should match 
// service_traits::MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStar > 
template<>
struct MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStar >::value();
  }
  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tsane_mmlamare_mwpiazza_lab4::AStarResponse> should match 
// service_traits::DataType< ::tsane_mmlamare_mwpiazza_lab4::AStar > 
template<>
struct DataType< ::tsane_mmlamare_mwpiazza_lab4::AStarResponse>
{
  static const char* value()
  {
    return DataType< ::tsane_mmlamare_mwpiazza_lab4::AStar >::value();
  }
  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TSANE_MMLAMARE_MWPIAZZA_LAB4_MESSAGE_ASTAR_H
