// Generated by gencpp from file tsane_mmlamare_mwpiazza_lab4/AStarRequest.msg
// DO NOT EDIT!


#ifndef TSANE_MMLAMARE_MWPIAZZA_LAB4_MESSAGE_ASTARREQUEST_H
#define TSANE_MMLAMARE_MWPIAZZA_LAB4_MESSAGE_ASTARREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <nav_msgs/OccupancyGrid.h>
#include <nav_msgs/OccupancyGrid.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace tsane_mmlamare_mwpiazza_lab4
{
template <class ContainerAllocator>
struct AStarRequest_
{
  typedef AStarRequest_<ContainerAllocator> Type;

  AStarRequest_()
    : frameID()
    , map()
    , costMap()
    , start()
    , goal()  {
    }
  AStarRequest_(const ContainerAllocator& _alloc)
    : frameID(_alloc)
    , map(_alloc)
    , costMap(_alloc)
    , start(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _frameID_type;
  _frameID_type frameID;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _map_type;
  _map_type map;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _costMap_type;
  _costMap_type costMap;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AStarRequest_

typedef ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<std::allocator<void> > AStarRequest;

typedef boost::shared_ptr< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest > AStarRequestPtr;
typedef boost::shared_ptr< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest const> AStarRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tsane_mmlamare_mwpiazza_lab4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30fda3ecfd4c5cc89f0b7662815f5231";
  }

  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30fda3ecfd4c5cc8ULL;
  static const uint64_t static_value2 = 0x9f0b7662815f5231ULL;
};

template<class ContainerAllocator>
struct DataType< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tsane_mmlamare_mwpiazza_lab4/AStarRequest";
  }

  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String frameID\n\
nav_msgs/OccupancyGrid map\n\
nav_msgs/OccupancyGrid costMap\n\
geometry_msgs/Pose start\n\
geometry_msgs/Pose goal\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: nav_msgs/OccupancyGrid\n\
# This represents a 2-D grid map, in which each cell represents the probability of\n\
# occupancy.\n\
\n\
Header header \n\
\n\
#MetaData for the map\n\
MapMetaData info\n\
\n\
# The map data, in row-major order, starting with (0,0).  Occupancy\n\
# probabilities are in the range [0,100].  Unknown is -1.\n\
int8[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frameID);
      stream.next(m.map);
      stream.next(m.costMap);
      stream.next(m.start);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AStarRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tsane_mmlamare_mwpiazza_lab4::AStarRequest_<ContainerAllocator>& v)
  {
    s << indent << "frameID: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.frameID);
    s << indent << "map: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.map);
    s << indent << "costMap: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.costMap);
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TSANE_MMLAMARE_MWPIAZZA_LAB4_MESSAGE_ASTARREQUEST_H
